# -*- coding: utf-8 -*-
"""Word Cloud generator app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVt4vy0D_M0IngrLdLCFPEIIgbakpsZd
"""

# App that displays wordcloud and lists frequent words when a pdf is uploaded

import numpy as np

import pandas as pd
import matplotlib.pyplot as plt

import pypdf

import nltk
import re
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

#pip install streamlit
import streamlit as st

# Streamlit UI
st.title("📘 PDF Word Analyzer")
st.write("Upload a PDF file to extract text, list frequent words, and view a word cloud.")

uploaded_file = st.file_uploader("Upload PDF", type="pdf")

if uploaded_file:
  # Assuming only one file is uploaded
  st.write("pdf uploaded successfully.")
  documents=[]
  reader=pypdf.PdfReader(uploaded_file) #read pdf
  text=""
  for page in reader.pages:
    text+=page.extract_text() or ''
  documents.append(text)   #extract text
else:
  st.write("Please upload a PDF file to proceed.")

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text

doc_txt=[preprocess_text(doc) for doc in documents]

from nltk.tokenize import word_tokenize

word=word_tokenize(str(doc_txt)) # word tokenization

from nltk.corpus import stopwords
english_stopwords=set(stopwords.words("english"))
word=[w for w in word if not w in english_stopwords] # remove stopwords
word=[w for w in word if len(w)>2] # Select words more than 2 characters
word=[w for w in word if w.isalnum()]

from nltk.probability import FreqDist

wordfreq=FreqDist(word)
st.subheader("📊 Top 20 Frequent Words")
st.write(wordfreq.most_common(20))

from wordcloud import WordCloud

wordcloud=WordCloud(width=1000,height=500,stopwords=english_stopwords,colormap="plasma",max_words=200).generate(str(word))

st.subheader("Word Cloud: ")
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear') #Word Cloud
plt.axis('off')
st.pyplot(plt)

